defaults:
  - finetune

handler: NullSpace
args: # HuggingFace TrainingArguments
  gradient_checkpointing_kwargs:  
    "use_reentrant": False
method_args:
  gamma: 1.0
  alpha: 1.0
  retain_loss_type: NLL
