model_args:
  # pretrained_model_name_or_path: "meta-llama/Llama-2-7b-hf"
  pretrained_model_name_or_path: "/home/cnz/.cache/huggingface/hub/models--meta-llama--Llama-2-7b-hf/snapshots/8cca527612d856d7d32bd94f8103728d614eb852"
  attn_implementation: 'flash_attention_2'
  torch_dtype: bfloat16
tokenizer_args:
  # pretrained_model_name_or_path: "meta-llama/Llama-2-7b-hf"
  pretrained_model_name_or_path: "/home/cnz/.cache/huggingface/hub/models--meta-llama--Llama-2-7b-hf/snapshots/8cca527612d856d7d32bd94f8103728d614eb852"
template_args:  # Used in creating prompts for the dataset. See src/data/utils.py#preprocess_chat_instance.
  apply_chat_template: False
  user_start_tag: "Question: "
  user_end_tag: "\n"
  asst_start_tag: "Answer: "
  asst_end_tag: "\n\n"